### ISSUE TITLE
Issues running the demo file

### ISSUE THREAD

**Issue by kgtekito** [t-sakai-kure/pywsl#1]
```
PNU/python/cpe_ene.py:49: RuntimeWarning: invalid value encountered in sqrt
  return np.sqrt(dist)
PNU/python/pnu_sl.py:152: RuntimeWarning: invalid value encountered in greater_equal
  f_p = np.mean(g_n >= 0) if n_n != 0 else 0
PNU/python/pnu_sl.py:161: RuntimeWarning: invalid value encountered in less_equal
  f_nu = np.mean(g_u <= 0) if n_u != 0 else 0
Traceback (most recent call last):
  File "./demo.py", line 64, in <module>
    model='lm', nargout=3)
  File "PNU/python/pnu_sl.py", line 92,in PNU_SL
    sigma, lam = sigma_list[best_sigma_index], lambda_list[best_lambda_index]
UnboundLocalError: local variable 'best_sigma_index' referenced before assignment
```
Hello, I've been trying to run the demo file, and encountered an error presented above.
any way to fix this? 
Thanks in advance.

**Comment by t-sakai-kure** [comment]
Hi, I presume that you modified the demo.py, e.g., you set eta_list at a certain scalar.
In the case, I can quickly modify the implementation.
Could you give more information about the input of PNU_SL function?
In particular, what kind of sigma_list, lambda_list, and eta_list caused the error.

**Comment by kgtekito** [comment]
Hello, 
I have not modified `demo.py` nor `pnu_sl` files in any way other than line ending conversion.
Is the file expected to run without any modification?

**Comment by t-sakai-kure** [comment]
I see.
Since the original code works on at least my environment, maybe, there are some compatibility issues.
Further information is necessary to identify the bug.

**Comment by kgtekito** [comment]
Thank you for your prompt response.
I've tried running this both on my OSX and ubuntu machines, both of which run anaconda3-4.0.0.
Are you certain that your original code is on the same version as the current master?

**Comment by t-sakai-kure** [comment]
To avoid the version issue, please retry the current version that I pushed today.
demo.py works on my environment, Python 3.5.2 :: Anaconda 4.2.0 (64-bit) on Windows 10.

**Comment by t-sakai-kure** [comment]
Hi, 
Now I can reproduce the error that you encountered. Since it relates to the random seed, I could not encounter it so far. I will modify this issue soon. Please wait for a while.

**Comment by t-sakai-kure** [comment]
HI, 
Could you try the updated code?
The bug occurred when the value of estimated class-prior became "nan".
Depending on the data, sometimes some elements of the matrix of squared distance takes negative. Then, the square root of negative value caused unexpected value, i.e., "nan", when estimating the class-prior.

**Comment by kgtekito** [comment]
It works on the updated code. thanks.

**Comment by t-sakai-kure** [comment]
Thank you for your report.
